const signalContent = {
  relaxed: { kicker: 'A softer read', title: 'Loose usually means comfortable.', summary: 'A relaxed dog can still be alert or excited. Look for easy movement and the ability to choose what happens next.', image: './assets/guide-relaxed.png', alt: 'A golden retriever sitting with a loose body, soft eyes, and an easy open mouth', items: [['Look for', 'Soft eyes, a wiggly middle, and a mouth that rests open or gently closed.'], ['Try this', 'Keep the moment predictable. Let your dog approach, sniff, or move away.'], ['Don’t assume', 'A wag only tells you the tail is moving—not whether the feeling is happy.'], ['Helpful next step', 'Notice what changed just before the body changed. Context is the missing clue.']] },
  playful: { kicker: 'An invitation', title: 'A play bow says “join me.”', summary: 'A true play bow usually comes with bouncy movement, a loose face, and room for the other dog to opt in or out.', image: './assets/guide-playful.png', alt: 'A small dog holding a clear play bow with its front legs down and hips raised', items: [['Look for', 'Front legs down, hips high, a curved or wiggly body, and a quick recovery after the bow.'], ['Try this', 'Match the energy with a short, low-pressure game and easy breaks.'], ['Don’t assume', 'A lowered front can also be a stretch or a way to make distance—check the rest of the body.'], ['Helpful next step', 'Give both dogs a chance to pause. Good play has give-and-take, not just pursuit.']] },
  interested: { kicker: 'Curiosity in motion', title: 'Alert is not the same as upset.', summary: 'A dog can notice something new and still feel okay. Check whether the body stays loose and whether your dog can disengage.', image: './assets/guide-interested.png', alt: 'A beagle standing with weight gently forward and ears tracking something interesting', items: [['Look for', 'Eyes and ears oriented toward a sound or object, with a mouth and body that remain flexible.'], ['Try this', 'Give your dog time to observe, then reward looking back at you or choosing to move on.'], ['Don’t assume', 'Forward ears or a lifted tail do not automatically mean confidence or aggression.'], ['Helpful next step', 'Watch the recovery: can your dog sniff, blink, eat, or respond after noticing the trigger?']] },
  unsure: { kicker: 'A small request', title: 'Turning away can be polite.', summary: 'Dogs often use tiny signals before bigger ones: a head turn, lip lick, sniff, or weight shift can mean “that is a lot.”', image: './assets/guide-uncertain.png', alt: 'A dog turning its head away with one paw lifted and ears angled back', items: [['Look for', 'A smaller posture, a closed mouth, looking away, or repeated displacement behaviors.'], ['Try this', 'Reduce the intensity and let your dog finish sniffing or create a little distance.'], ['Don’t assume', 'Yawning is not always tiredness; in context it can be a way to release pressure.'], ['Helpful next step', 'Respect the first quiet signal. It is useful communication, not bad behavior.']] },
  stressed: { kicker: 'Stress is a pattern', title: 'Busy bodies may be asking for less.', summary: 'Panting, pacing, shaking, lip licking, yawning, or scanning can signal stress—especially when they repeat or cluster together.', image: './assets/guide-stressed.png', alt: 'A dog sitting with a lip lick, shifting ears, and a slightly tense posture', items: [['Look for', 'Difficulty settling, repeated displacement behaviors, rapid breathing, or trying to get away.'], ['Try this', 'Lower noise and activity, add distance, and offer a predictable place to rest.'], ['Don’t assume', 'Panting is not always heat or exercise; check the environment and what happened just before.'], ['Helpful next step', 'If stress is frequent, sudden, or paired with pain or illness signs, ask a veterinarian for help.']] },
  fearful: { kicker: 'Fear needs choice', title: 'Small and still can mean “I feel unsafe.”', summary: 'A fearful dog may hide, crouch, tuck the tail, freeze, or try to flee. The kindest response is more control and less pressure.', image: './assets/guide-fearful.png', alt: 'A small dog crouched low with its tail tucked in a safe corner near an open exit', items: [['Look for', 'Low posture, tucked tail, ears back, avoiding eye contact, trembling, hiding, or escape attempts.'], ['Try this', 'Move away, keep your body turned sideways, and let your dog choose a safe distance.'], ['Don’t assume', 'A dog who freezes is not necessarily calm; freezing can come before flight or defensive behavior.'], ['Helpful next step', 'Use reward-based support and never force greetings, handling, or exposure.']] },
  overwhelmed: { kicker: 'A clear boundary', title: 'Stillness can be a stop sign.', summary: 'A frozen body, hard stare, tight mouth, or weight pushed forward deserves space. A dog who cannot leave may escalate.', image: './assets/guide-needs-space.png', alt: 'A dog standing still with a tight mouth, turned head, and body leaning back to ask for space', items: [['Look for', 'Sudden stillness, stiffness, intense focus, lifted lip, growl, or a tail held very high and tight.'], ['Try this', 'Stop the interaction, turn away, and create distance without scolding or grabbing.'], ['Don’t assume', 'A growl is not “being bad.” It is valuable information that the situation is too much.'], ['Helpful next step', 'If this pattern repeats, get support from a reward-based behavior professional.']] },
  warning: { kicker: 'Stop and create distance', title: 'Strong warnings are safety information.', summary: 'A stiff body, hard stare, growl, snap, or lunge means the situation is too intense. Give space immediately and avoid punishment.', image: './assets/guide-warning.png', alt: 'A dog in a stiff side profile with hard focus and a lifted lip showing a clear warning', items: [['Look for', 'Sudden stillness, rigid posture, hard focus, lifted lip, teeth, growling, snapping, or lunging.'], ['Try this', 'Stop reaching or approaching, turn away, and create a clear exit without grabbing the collar.'], ['Don’t assume', 'A warning is not a character flaw. Punishing it can remove the warning without changing the feeling.'], ['Helpful next step', 'For repeated or high-risk behavior, work with a qualified reward-based behavior professional.']] }
};

const cards = document.querySelectorAll('.signal-card');
const kicker = document.getElementById('read-kicker');
const title = document.getElementById('read-title');
const summary = document.getElementById('read-summary');
const readImage = document.getElementById('read-image');
const list = document.getElementById('read-list');

function selectSignal(key) {
  const signal = signalContent[key];
  cards.forEach((card) => card.setAttribute('aria-pressed', String(card.dataset.signal === key)));
  kicker.textContent = signal.kicker;
  title.textContent = signal.title;
  summary.textContent = signal.summary;
  readImage.src = signal.image;
  readImage.alt = signal.alt;
  list.innerHTML = signal.items.map(([label, copy]) => `<li><strong>${label}</strong><span>${copy}</span></li>`).join('');
}

cards.forEach((card) => card.addEventListener('click', () => selectSignal(card.dataset.signal)));
