const signalContent = {
  'soft-eyes': { category: 'Face', kicker: 'Face & eyes', title: 'Relaxed / happy: soft eyes', summary: 'A soft gaze with easy blinking is one piece of a comfortable-looking pattern.', image: './assets/guide-relaxed.webp', alt: 'Golden retriever with soft eyes and a relaxed open mouth', see: 'Soft eyelids, a flexible gaze, and facial muscles that do not look pulled tight.', check: 'Loose posture, easy breathing, and whether the dog can look away or move freely.', meaning: 'In this context, the combination may be consistent with comfort or friendly attention.', avoid: 'Do not read a soft face without checking the body, tail, movement, and situation.', response: 'Keep the moment predictable and let the dog choose whether to approach, sniff, or pause.', help: 'Seek help for sudden eye changes, pain signs, or a major change from the dog’s normal baseline.', related: ['See the relaxed pattern', './signals.html?signal=loose-posture'] },
  'hard-stare': { category: 'Face', kicker: 'Face & eyes', title: 'Hard or fixed stare', summary: 'A still, intense gaze can be a sign that the dog is concentrating, worried, guarding, or asking for distance.', image: './assets/guide-warning.webp', alt: 'Dog showing an intense fixed gaze with a stiff body and raised lip', see: 'Eyes held on one target with little blinking, often paired with facial or body stillness.', check: 'Mouth tension, weight distribution, tail height, and what the dog is looking at.', meaning: 'A hard stare can signal rising pressure or a serious boundary in this context.', avoid: 'Do not challenge the stare, stare back, or assume it always predicts a bite.', response: 'Stop moving closer, turn slightly sideways, and create a safe exit.', help: 'Get qualified help when hard stares repeat, guard resources, or occur around children or visitors.', related: ['Read needs-space signals', './signals.html?signal=freeze'] },
  'looking-away': { category: 'Face', kicker: 'Face & eyes', title: 'Not so sure: looking away', summary: 'A head or eye turn can be a quiet way to reduce social pressure or gather information.', image: './assets/guide-uncertain.webp', alt: 'Dog looking away with one paw lifted and ears angled back', see: 'Eyes or head turning away, a closed mouth, or a pause during an interaction.', check: 'Whether the dog can leave, sniff, eat, and return voluntarily.', meaning: 'The dog may be uncertain, conflicted, or politely asking for a little less intensity.', avoid: 'Do not force eye contact or pull the head back toward you.', response: 'Pause, soften your body, and give the dog room to finish the choice.', help: 'Ask for support if avoidance becomes constant, sudden, or connected to pain.', related: ['Try the child-reaches scenario', './scenarios.html'] },
  'whale-eye': { category: 'Face', kicker: 'Face & eyes', title: 'Visible eye whites', summary: 'A widened eye with white showing at the edge can appear when a dog is worried and trying to monitor a situation.', image: './assets/guide-stressed.webp', alt: 'Dog showing a wide side glance with visible eye white and a tense mouth', see: 'The eye looks wide and the white crescent may show as the dog looks sideways.', check: 'Ears, mouth, head position, distance, and whether the dog is being held or cornered.', meaning: 'In a tense context, this may be a request for space or a sign of conflict.', avoid: 'Do not label every visible eye white as fear; some eyes and face shapes show more white naturally.', response: 'Stop reaching and increase space without making the dog feel chased.', help: 'Seek guidance if this appears during handling or alongside snapping, freezing, or pain.', related: ['Read the uncertain pattern', './signals.html?signal=leaning-away'] },
  'neutral-ears': { category: 'Ears', kicker: 'Ears & head', title: 'Neutral ears', summary: 'Ears resting in the dog’s usual position are a baseline clue, not a complete emotional label.', image: './assets/guide-relaxed.webp', alt: 'Golden retriever with ears resting naturally and a loose body', see: 'Ears resting where they normally sit for that individual dog.', check: 'The dog’s baseline, facial softness, posture, tail, movement, and the setting.', meaning: 'Neutral ears can fit many states, including relaxed, mildly interested, or simply at rest.', avoid: 'Do not compare floppy, upright, cropped, or heavily coated ears as if they communicate identically.', response: 'Learn the dog’s normal baseline and watch for changes from it.', help: 'Ask a veterinarian about sudden ear carriage changes with scratching, pain, or head shaking.', related: ['Learn about breed and baseline', './body-map.html'] },
  'ears-forward': { category: 'Ears', kicker: 'Ears & head', title: 'Interested / alert: tracking', summary: 'The head, eyes, and available ear movement orient toward something interesting; floppy ears may show the change subtly.', image: './assets/guide-interested.webp', alt: 'Beagle oriented toward a butterfly with its head and weight gently forward', see: 'Head and eyes point toward a sound or object; the ears may orient as far as that dog’s anatomy allows.', check: 'Whether the rest of the body stays loose and whether the dog can disengage.', meaning: 'The dog may be interested or alert; the signal alone does not tell you whether they feel safe.', avoid: 'Do not expect every dog’s ears to stand forward or equate alertness with confidence, dominance, or aggression.', response: 'Give the dog time to observe and reward a calm look back or easy turn away.', help: 'Get support if attention becomes rigid, frantic, or difficult to interrupt safely.', related: ['Read alert tracking', './signals.html?signal=weight-forward'] },
  'ears-back': { category: 'Ears', kicker: 'Ears & head', title: 'Fearful: ears back', summary: 'Ears back can occur with fear, appeasement, stress, pain, or relaxed social softness depending on the whole dog.', image: './assets/guide-fearful.webp', alt: 'Small dog crouched with ears pulled back and tail tucked', see: 'Ears held back from the dog’s normal position, sometimes pressed close to the head.', check: 'Eye shape, mouth, posture, tail, movement, and whether the dog can escape.', meaning: 'With a low body or retreat, this combination may be consistent with fear or stress.', avoid: 'Do not assign one meaning to ears back across every dog or situation.', response: 'Lower pressure, turn sideways, and offer distance and a protected place.', help: 'Seek professional or veterinary help if the change is sudden or handling becomes unsafe.', related: ['Read the fearful pattern', './signals.html?signal=crouching'] },
  'head-turn': { category: 'Ears', kicker: 'Ears & head', title: 'Head turn', summary: 'Turning the head away can interrupt pressure and is often an early signal worth respecting.', image: './assets/guide-uncertain.webp', alt: 'Dog turning its head away with a lifted paw and uncertain expression', see: 'The nose points away from a person, dog, object, or touch.', check: 'Whether the mouth tightens, the body leans away, or the dog returns by choice.', meaning: 'The dog may be unsure, conflicted, or asking for a slower interaction.', avoid: 'Do not keep moving into the dog’s space because they have not walked away yet.', response: 'Pause and make it easy for the dog to move away or re-approach.', help: 'Get support when head turns escalate to freezing, growling, or defensive movement.', related: ['Read looking away', './signals.html?signal=looking-away'] },
  'lowered-head': { category: 'Ears', kicker: 'Ears & head', title: 'Lowered head', summary: 'A lowered head can be an invitation to sniff, a response to pressure, or part of a fearful smaller posture.', image: './assets/guide-fearful.webp', alt: 'Dog holding its head low while crouched near a safe exit', see: 'Head and neck lower, sometimes with the eyes looking upward or away.', check: 'Spine, legs, tail, breathing, and whether the dog moves closer or away.', meaning: 'Context determines whether it is exploration, uncertainty, fear, or a calming pause.', avoid: 'Do not reach over a lowered head or assume the dog wants to be touched.', response: 'Use a softer angle, give space, and invite rather than insist.', help: 'Ask a veterinarian about sudden lowering with pain, weakness, or reluctance to move.', related: ['Read making the body smaller', './signals.html?signal=make-smaller'] },
  'relaxed-mouth': { category: 'Mouth', kicker: 'Mouth', title: 'Relaxed open mouth', summary: 'A loose open mouth can fit comfort, warmth, exercise, or excitement—context changes the read.', image: './assets/guide-relaxed.webp', alt: 'Golden retriever with a loose open mouth and soft facial muscles', see: 'Jaw and lips look loose rather than pulled tight; the tongue may rest naturally.', check: 'Breathing, temperature, recent exercise, eyes, posture, and recovery.', meaning: 'Alongside a loose body and easy movement, it may be consistent with comfort.', avoid: 'Do not use an open mouth alone as proof that the dog is happy.', response: 'Keep observing the whole pattern and provide water, shade, or a break when needed.', help: 'Seek veterinary help for abnormal panting, breathing difficulty, heat concern, or sudden change.', related: ['Read panting in context', './signals.html?signal=panting-context'] },
  'closed-mouth': { category: 'Mouth', kicker: 'Mouth', title: 'Closed or tight mouth', summary: 'A mouth that suddenly closes and tightens can be an early sign that the situation changed.', image: './assets/guide-needs-space.webp', alt: 'Dog with a closed tight mouth and a body asking for more space', see: 'Lips press together or the mouth closes after being loose, often with facial stillness.', check: 'Eyes, ears, body stiffness, tail, trigger, and ability to move away.', meaning: 'The dog may be concentrating, uncertain, or uncomfortable with what is happening.', avoid: 'Do not treat the closed mouth as a minor detail when it appears with a freeze.', response: 'Stop adding pressure and create a clear, calm exit.', help: 'Get professional help when tight-mouth responses are frequent or escalate.', related: ['Read the freeze', './signals.html?signal=freeze'] },
  'lip-licking': { category: 'Mouth', kicker: 'Mouth', title: 'Lip licking', summary: 'A quick tongue flick can be normal after food, but repeated lip licking in a tense moment may release pressure.', image: './assets/guide-stressed.webp', alt: 'Dog showing a visible tongue flick with shifting ears in a park', see: 'A quick tongue flick, often paired with a head turn, ears back, or a closed mouth.', check: 'What happened just before it, repetition, posture, and whether food or nausea is involved.', meaning: 'In a social or handling context, it may be a stress or conflict signal.', avoid: 'Do not assume every lick means guilt, hunger, or disobedience.', response: 'Pause the interaction and give the dog a lower-pressure option.', help: 'Ask a veterinarian about frequent licking with drooling, nausea, pain, or appetite changes.', related: ['Read stress patterns', './signals.html?signal=stressed-pattern'] },
  'panting-context': { category: 'Mouth', kicker: 'Mouth', title: 'Panting in context', summary: 'Panting can cool a dog after effort, but stress, pain, heat, medication, and illness can also cause it.', image: './assets/guide-relaxed.webp', alt: 'Golden retriever with an open mouth after activity in a sunny park', see: 'Fast breathing or an open mouth that continues after the obvious reason has passed.', check: 'Heat, exercise, fear, pain signs, gums, posture, and how quickly the dog recovers.', meaning: 'The meaning is uncertain without the setting and the dog’s baseline.', avoid: 'Do not label panting as happiness or anxiety from one still image.', response: 'Offer water, shade, rest, and distance from a stressful trigger.', help: 'Contact a veterinarian promptly for unexplained, intense, or sudden panting.', related: ['Read stressed / anxious', './signals.html?signal=stressed-pattern'] },
  'teeth-display': { category: 'Mouth', kicker: 'Mouth & warning', title: 'Teeth display', summary: 'Showing teeth is a clear request for more distance when paired with tension or a hard focus.', image: './assets/guide-warning.webp', alt: 'Dog showing teeth with a rigid body and hard focus', see: 'Lifted lips expose teeth, often with a tight mouth, stillness, or growl.', check: 'Whole posture, tail, eyes, distance, guarding context, and the dog’s exit route.', meaning: 'The dog is communicating that the situation is too intense or unsafe for them.', avoid: 'Do not punish, corner, grab, or test the warning.', response: 'Stop approaching, create distance, and move people or animals away safely.', help: 'Get qualified behavior and veterinary support for repeated or high-risk warning signals.', related: ['Read strong warnings', './signals.html?signal=growling'] },
  'loose-tail': { category: 'Tail', kicker: 'Tail', title: 'Loose tail movement', summary: 'A broad, flexible tail movement is more useful when read with a soft body and easy recovery.', image: './assets/guide-playful.webp', alt: 'Dog with a visibly loose tail and a springy play posture', see: 'Tail moves in a broad, flexible arc while the body remains wiggly.', check: 'Tail height, speed, spine, mouth, eyes, and whether the dog can disengage.', meaning: 'This combination may fit play or friendly excitement, not a guaranteed yes to interaction.', avoid: 'Do not translate “wagging” into “happy” without reading the rest of the dog.', response: 'Allow pauses and choices; invite interaction rather than forcing it.', help: 'Seek support when tail movement comes with stiffness, guarding, or sudden behavior change.', related: ['Read the play bow', './signals.html?signal=play-bow'], searchTerms: ['tail wag', 'tail wagging', 'wagging tail', 'tail wag means happy', 'tail wag always happy'] },
  'low-tail': { category: 'Tail', kicker: 'Tail', title: 'Low tail', summary: 'A low tail may show uncertainty, relaxation, fatigue, or an individual’s normal carriage.', image: './assets/guide-uncertain.webp', alt: 'Dog with a low tail and uncertain head turn', see: 'Tail carried lower than the dog’s usual baseline without necessarily being tucked.', check: 'Eyes, ears, weight shift, mouth, movement, and what just changed.', meaning: 'It may be a small request for space when paired with avoidance or a smaller body.', avoid: 'Do not compare tail height across breeds with different natural carriage.', response: 'Slow down and give the dog a choice to move away or investigate.', help: 'Ask a veterinarian about sudden tail carriage changes or pain near the back or tail.', related: ['Learn the dog’s baseline', './body-map.html'] },
  'tucked-tail': { category: 'Tail', kicker: 'Tail', title: 'Tucked tail', summary: 'A tail pulled tightly under the body often appears with fear, strong uncertainty, or a need to escape.', image: './assets/guide-tucked-tail.webp', alt: 'Small dog crouched with its tail clearly curled tightly under its belly', see: 'Tail curls visibly under the belly and is held tightly between or against the hind legs.', check: 'Crouch, ears, eyes, trembling, hiding, and whether the dog can get away.', meaning: 'The cluster may be consistent with fear or a high need for safety.', avoid: 'Do not pull the tail out, approach faster, or force a greeting.', response: 'Increase distance and give access to a quiet protected place.', help: 'Seek reward-based behavior support; contact a veterinarian if fear is sudden or pain-related.', related: ['Read fearful signals', './signals.html?signal=crouching'] },
  'high-stiff-tail': { category: 'Tail', kicker: 'Tail', title: 'High, stiff tail', summary: 'A tail held high and rigid can signal arousal or tension; it is not a universal sign of confidence.', image: './assets/guide-warning.webp', alt: 'Dog with a high rigid tail, stiff body, and warning expression', see: 'Tail held high with little flexible movement, sometimes paired with a rigid spine.', check: 'Hard stare, mouth tension, weight, hackles, trigger, and recovery.', meaning: 'The dog may be highly aroused, guarding, or preparing to increase distance.', avoid: 'Do not approach because the tail is up or assume the dog is dominant.', response: 'Create distance and remove pressure without grabbing or scolding.', help: 'Get professional help when stiffness repeats or appears around people, dogs, food, or handling.', related: ['Read the warning combination', './signals.html?signal=warning-combination'] },
  'fast-tight-wag': { category: 'Tail', kicker: 'Tail', title: 'High tail, activated body', summary: 'A raised tail and forward weight can show activation; a still image cannot tell you how fast the tail is moving.', image: './assets/guide-interested.webp', alt: 'Alert dog with an upright tail while watching a butterfly', see: 'Tail is held high while the head and weight point toward something interesting.', check: 'Body stiffness, eyes, mouth, distance, and whether the dog can turn away.', meaning: 'The dog is activated; context tells you whether that activation is playful, worried, or defensive.', avoid: 'Do not say “the tail is up, so it is safe,” and do not infer speed from a still image.', response: 'Lower intensity and look for a softening or voluntary disengagement.', help: 'Seek guidance for recurring high arousal or unsafe reactions.', related: ['Read high-tail activation', './signals.html?signal=weight-forward'], searchTerms: ['tight tail wag', 'fast tail wag', 'tail wag means happy', 'wagging tail safe'] },
  'loose-posture': { category: 'Body', kicker: 'Body & posture', title: 'Loose posture', summary: 'Flexible muscles, a curved body, and easy movement make a more comfortable-looking pattern.', image: './assets/guide-relaxed.webp', alt: 'Golden retriever sitting with a loose body, soft eyes, and relaxed tail', see: 'Muscles look soft, weight shifts easily, and the body can wiggle or curve.', check: 'Face, ears, tail, breathing, and whether the dog can choose to leave.', meaning: 'The combination may be consistent with comfort in that setting.', avoid: 'Do not freeze the dog into one label; comfort can change quickly with context.', response: 'Keep choices open and reward calm check-ins without demanding contact.', help: 'Ask a veterinarian about sudden stiffness, weakness, or reluctance to move.', related: ['Read the relaxed pattern', './signals.html?signal=soft-eyes'] },
  'play-bow': { category: 'Body', kicker: 'Body & posture', title: 'Ready to play: play bow', summary: 'A lowered front with raised hips can invite play when the body and movement stay loose.', image: './assets/guide-playful.webp', alt: 'Small dog holding a clear play bow with front legs down and hips raised', see: 'Front end lowers while the hips stay up, often with a wiggly body or bouncy recovery.', check: 'Pauses, turn-taking, loose mouth, and freedom for both dogs to leave.', meaning: 'This pattern is more consistent with an invitation than a demand when both dogs stay flexible.', avoid: 'Do not assume every lowered front is play; it can also be a stretch or distance-making signal.', response: 'Offer a short game and build in easy breaks.', help: 'Get help if play repeatedly becomes one-sided, frightening, or unsafe.', related: ['Read playful movement', './signals.html?signal=bouncy-movement'] },
  'weight-forward': { category: 'Body', kicker: 'Body & posture', title: 'Weight forward', summary: 'A body leaning toward something shows attention or arousal, not a complete emotional diagnosis.', image: './assets/guide-interested.webp', alt: 'Beagle standing with weight forward while noticing a butterfly', see: 'Chest and weight shift toward a sound, object, person, or animal.', check: 'Ears, tail, mouth, stiffness, distance, and ability to look away.', meaning: 'The dog may be curious, excited, frustrated, or concerned depending on the trigger.', avoid: 'Do not confuse forward weight with permission to approach.', response: 'Keep enough distance for the dog to observe and return attention to you.', help: 'Seek help if forward movement becomes lunging or difficult to interrupt safely.', related: ['Read interested / alert', './signals.html?signal=ears-forward'] },
  'leaning-away': { category: 'Body', kicker: 'Body & posture', title: 'Leaning away', summary: 'A weight shift away from a person, object, or touch can be an early request for space.', image: './assets/guide-uncertain.webp', alt: 'Dog leaning away while turning its head and lifting one paw', see: 'Shoulders or hips move away while the dog keeps watching the situation.', check: 'Head turn, mouth, paw lift, tail, and whether pressure continues.', meaning: 'The dog may be uncertain or conflicted and trying to avoid escalation.', avoid: 'Do not follow the lean or hold the dog in place.', response: 'Stop reaching and give the dog a clear path away.', help: 'Get support when leaning away appears during grooming, handling, or child contact.', related: ['Read the handling scenario', './scenarios.html'] },
  'crouching': { category: 'Body', kicker: 'Body & posture', title: 'Crouching', summary: 'A lowered body can help a dog feel smaller when they are worried or trying to avoid attention.', image: './assets/guide-fearful.webp', alt: 'Small dog crouched low with ears back and tail tucked', see: 'Legs bend, spine lowers, and weight may shift back or toward an escape route.', check: 'Tail, eyes, ears, trembling, hiding, and whether the dog can leave.', meaning: 'This cluster may be consistent with fear or overwhelm.', avoid: 'Do not bend over the dog, reach into the corner, or insist on touch.', response: 'Move away, reduce noise, and protect the dog’s escape route.', help: 'Contact a qualified behavior professional for persistent fear or defensive reactions.', related: ['Read tucked tail', './signals.html?signal=tucked-tail'] },
  'make-smaller': { category: 'Body', kicker: 'Body & posture', title: 'Making the body smaller', summary: 'A dog may lower, curl, or fold the body to reduce social pressure.', image: './assets/guide-fearful.webp', alt: 'Dog curled into a smaller posture in a quiet corner', see: 'Back rounds, head lowers, legs tuck in, and the dog takes up less space.', check: 'Breathing, eye movement, tail, exit route, and whether the dog is freezing.', meaning: 'The dog may be frightened, conflicted, or trying hard not to be noticed.', avoid: 'Do not interpret stillness as agreement or calm just because the dog is quiet.', response: 'Give space and let the dog recover without forced reassurance.', help: 'Seek professional support if the dog cannot recover or safety is becoming difficult.', related: ['Read fear and freezing', './signals.html?signal=freeze'] },
  freeze: { category: 'Body', kicker: 'Body & posture', title: 'Needs space: freeze', summary: 'Stillness is not proof of calm. A freeze can be a pause before flight, a warning, or an overwhelmed dog running out of options.', image: './assets/guide-needs-space.webp', alt: 'Dog standing very still with a tight mouth while asking for space', see: 'Movement stops suddenly and muscles or mouth become tight.', check: 'Eyes, ears, tail, weight, trigger, and whether the dog has an exit.', meaning: 'In a pressure-filled context, the dog may be asking for the interaction to stop.', avoid: 'Do not pet, corner, reach, or test what happens next.', response: 'Stop adding pressure and create distance while keeping people safe.', help: 'Get qualified help for repeated freezing, snapping, guarding, or sudden changes.', related: ['Read the hard stare', './signals.html?signal=hard-stare'] },
  'paw-lift': { category: 'Body', kicker: 'Body & posture', title: 'Paw lift', summary: 'A lifted paw can show attention, uncertainty, learned asking, or a normal breed tendency.', image: './assets/guide-uncertain.webp', alt: 'Dog lifting one front paw while looking away uncertainly', see: 'One front paw lifts and the dog pauses or shifts weight.', check: 'Face, ears, body direction, trigger, and whether the dog can move away.', meaning: 'In this context it may be a small hesitation or conflict signal.', avoid: 'Do not call it anxiety from the paw alone; always compare with the rest of the dog.', response: 'Slow the interaction and offer a simple choice to approach or leave.', help: 'Ask a veterinarian about a new persistent paw lift, lameness, or pain.', related: ['Read uncertain signals', './signals.html?signal=looking-away'] },
  'raised-hackles': { category: 'Body', kicker: 'Body & posture', title: 'Raised hackles', summary: 'Hair standing up along the back shows arousal, not one specific emotion.', image: './assets/guide-warning.webp', alt: 'Dog with raised fur along its back and a tense warning expression', see: 'Fur lifts along the shoulders or spine, sometimes called piloerection.', check: 'Eyes, mouth, body stiffness, tail, trigger, and recovery.', meaning: 'The dog is activated; the reason may be excitement, fear, surprise, or defensiveness.', avoid: 'Do not treat raised hackles as automatic aggression.', response: 'Increase space and watch whether the body softens or intensifies.', help: 'Get professional help if raised arousal repeatedly becomes unsafe.', related: ['Read high arousal', './signals.html?signal=warning-combination'] },
  'bouncy-movement': { category: 'Movement', kicker: 'Movement & distance', title: 'Bouncy movement', summary: 'Springy movement and easy pauses often support a play read when the body stays loose.', image: './assets/behavior-zoomies.webp', alt: 'Happy dog running in a safe grassy yard with loose movement', see: 'Curves, quick direction changes, and a body that can pause and restart.', check: 'Turn-taking, mouth, ears, recovery, and whether anyone is trying to escape.', meaning: 'The dog may be releasing energy or inviting play in a safe setting.', avoid: 'Do not assume every fast run is joy; frantic movement can also be overwhelm.', response: 'Clear hazards and add pauses before the dog becomes over-aroused.', help: 'Seek help if movement is frantic, repetitive, or paired with panic or injury.', related: ['Read zoomies and recovery', './behaviors.html'] },
  'approach-retreat': { category: 'Movement', kicker: 'Movement & distance', title: 'Approach, then pause', summary: 'A dog may investigate and then pause, turn away, or lift a paw when interest and uncertainty overlap.', image: './assets/guide-uncertain.webp', alt: 'Dog pausing with a lifted paw and body angled away', see: 'The dog pauses, turns its head, or angles the body away while still monitoring the situation.', check: 'Trigger distance, facial tension, tail, and whether the dog chooses another approach.', meaning: 'The dog may want information while still needing more safety or time.', avoid: 'Do not lure the dog closer or remove the option to retreat.', response: 'Stay still, add space, and let the dog set the pace.', help: 'Get support if approach-and-pause cycles become frantic or defensive.', related: ['Read uncertain signals', './signals.html?signal=leaning-away'] },
  'backing-away': { category: 'Movement', kicker: 'Movement & distance', title: 'Angling away', summary: 'A body angled away can be an early request for distance, especially when the dog cannot turn or leave freely.', image: './assets/guide-needs-space.webp', alt: 'Dog angled away with a closed mouth and a low tail', see: 'Shoulders or body point away from the trigger while the dog keeps monitoring it.', check: 'Exit route, mouth, eyes, ears, tail, and whether someone is following.', meaning: 'The dog may be uncomfortable and trying to prevent the situation from escalating.', avoid: 'Do not follow, corner, or hold the dog in place.', response: 'Stop and open a path away from the trigger.', help: 'Seek professional support when avoidance is frequent or paired with warning signals.', related: ['Read needs-space signals', './signals.html?signal=freeze'] },
  hiding: { category: 'Movement', kicker: 'Movement & distance', title: 'Hiding or avoiding', summary: 'A dog choosing a bed, corner, or person’s legs may be recovering, avoiding pressure, or feeling unwell.', image: './assets/guide-fearful.webp', alt: 'Small dog hiding beside furniture while keeping an exit visible', see: 'The dog moves behind furniture, under a table, or away from people and animals.', check: 'Whether the dog can rest, eat, come out voluntarily, and what changed.', meaning: 'The dog may need safety and recovery; a sudden change can also have a health cause.', avoid: 'Do not pull the dog out or turn the hiding place into a trap.', response: 'Protect the safe spot and reduce whatever is causing pressure.', help: 'Contact a veterinarian for sudden persistent hiding, pain, appetite changes, or lethargy.', related: ['Read resting and hiding', './behaviors.html'] },
  'moving-closer': { category: 'Movement', kicker: 'Movement & distance', title: 'Choosing to stay near', summary: 'A dog resting near you with a loose body may be comfortable in that moment, but proximity is not permanent consent.', image: './assets/guide-relaxed.webp', alt: 'Relaxed dog sitting alone with a loose body and soft eyes', see: 'The dog stays nearby with a loose body and can still turn away or leave.', check: 'Softness, pauses, sniffing, and whether the dog returns after a break.', meaning: 'The dog may be comfortable enough to share space or investigate in that moment.', avoid: 'Do not assume proximity means the dog wants hugging, restraint, or continuous touch.', response: 'Keep contact brief and let the dog choose what happens next.', help: 'Ask for support if calm proximity quickly flips to freezing, growling, or snapping.', related: ['Learn consent-based handling', './training.html'] },
  growling: { category: 'Warnings', kicker: 'Vocal + body warning', title: 'Strong warning: growling', summary: 'A growl is communication about discomfort, conflict, guarding, fear, pain, or arousal—not a moral failure.', image: './assets/guide-warning.webp', alt: 'Dog growling with a stiff body and visible teeth', see: 'Low vocalization, often paired with stillness, hard focus, tight mouth, or a lifted lip.', check: 'Trigger, distance, posture, tail, exit route, and what happened before the sound.', meaning: 'The dog is telling you the current situation is too much or too close.', avoid: 'Never punish the growl or remove it without addressing the underlying problem.', response: 'Stop pressure, create distance, and separate people or animals safely.', help: 'Get qualified behavior and veterinary help for repeated, sudden, or high-risk growling.', related: ['Read guarding', './scenarios.html'] },
  snarling: { category: 'Warnings', kicker: 'Vocal + body warning', title: 'Snarl or lifted lip', summary: 'A snarl combines a vocal or facial warning with visible mouth tension and deserves immediate space.', image: './assets/guide-warning.webp', alt: 'Dog snarling with lifted lip, hard eyes, and a rigid body', see: 'Lip lifts, teeth show, and the face or body may become very still.', check: 'Whole posture, trigger, distance, and whether the dog can escape.', meaning: 'The dog is communicating a high level of discomfort or defensive arousal.', avoid: 'Do not stare, scold, reach toward the collar, or test the warning.', response: 'Back away calmly and manage the environment so the dog has space.', help: 'Contact a qualified professional promptly, especially after a bite or near-bite.', related: ['Read teeth display', './signals.html?signal=teeth-display'] },
  barking: { category: 'Warnings', kicker: 'Vocal + body context', title: 'Barking with body clues', summary: 'Barking can alert, invite, frustrate, frighten, or ask for help; the body and recovery explain more.', image: './assets/behavior-barking.webp', alt: 'Dog barking toward a distant van with ears and body oriented forward', see: 'Vocalizing with a visible direction, posture, tail, and movement pattern.', check: 'Rhythm, distance, trigger, mouth, weight, and whether the dog can recover.', meaning: 'The dog may be activated for many different reasons; one bark pattern is not universal.', avoid: 'Do not assume barking means dominance or punish without understanding the trigger.', response: 'Add distance, lower stimulation, and reward quiet check-ins when safe.', help: 'Seek help when barking is persistent, sudden, or paired with lunging or distress.', related: ['Explore barking behavior', './behaviors.html'] },
  lunging: { category: 'Warnings', kicker: 'Vocal + body warning', title: 'Lunging', summary: 'A lunge is a high-arousal movement toward or away from a trigger and needs management before training.', image: './assets/challenge-lunging.webp', alt: 'Dog lunging on leash toward a distant dog while a handler creates space', see: 'Leash reaches tight, front feet drive forward, and the dog may bark or vocalize.', check: 'Trigger distance, recovery, ability to eat, and secure equipment.', meaning: 'The dog may be frightened, frustrated, overexcited, or trying to make the trigger move away.', avoid: 'Do not wait for a full reaction or punish the dog at close range.', response: 'Turn away early, create distance, and keep everyone secure.', help: 'Work with a qualified reward-based professional for repeated lunging or bite risk.', related: ['Read barking and lunging', './challenges.html'] },
  'guarding-freeze': { category: 'Warnings', kicker: 'Vocal + body warning', title: 'Guarding freeze', summary: 'Freezing over food or an object is an early warning that the dog may fear losing something valuable.', image: './assets/challenge-guarding.webp', alt: 'Dog beside a food bowl while a handler gives space', see: 'Body hovers over the item, movement stops, and eyes may harden toward an approaching person.', check: 'Distance, mouth, growl, item value, and whether the dog can leave.', meaning: 'The dog is asking for space around a resource, not plotting to be difficult.', avoid: 'Never reach into the bowl, grab the item, or punish the warning.', response: 'Back away, manage meals behind a barrier, and use a professional trade plan.', help: 'Get qualified behavior help for repeated guarding, children, or any snap or bite.', related: ['Read food guarding', './challenges.html'] }
};

Object.assign(signalContent, {
  'stressed-pattern': { category: 'Body', kicker: 'Whole-body pattern', title: 'Stressed / anxious: a cluster', summary: 'Stress is easier to read as a cluster than as one isolated gesture.', image: './assets/guide-stressed.webp', alt: 'Dog showing a tongue flick, wide eyes, and a tense posture', see: 'Repeated lip licking, scanning, fast breathing, pacing, lowered posture, or difficulty settling.', check: 'What changed, whether the dog can eat or sniff, and how quickly they recover.', meaning: 'The combination may be consistent with stress or anxiety in this situation.', avoid: 'Do not label every pant, yawn, or lick as stress without considering heat, exercise, food, or health.', response: 'Lower stimulation, add distance, and give the dog a predictable recovery space.', help: 'Contact a veterinarian for sudden or unexplained changes and a qualified professional for recurring distress.', related: ['Read panting in context', './signals.html?signal=panting-context'] },
  'warning-combination': { category: 'Warnings', kicker: 'Whole-body pattern', title: 'Strong warning: the whole pattern', summary: 'Stiffness, hard focus, tight mouth, and vocal or teeth signals mean pressure is too high.', image: './assets/guide-warning.webp', alt: 'Dog showing a stiff body, hard focus, raised hackles, and visible teeth', see: 'Rigid posture, hard eyes, a tight mouth, raised fur, growling, snarling, snapping, or lunging.', check: 'Distance, trigger, exit route, and whether people or animals can move away safely.', meaning: 'The dog is communicating a high need for space; the image cannot predict exactly what they will do next.', avoid: 'Do not punish, corner, grab, stare at, or test a warning.', response: 'Stop pressure and create distance while managing the environment safely.', help: 'Seek qualified behavior and veterinary support for repeated, sudden, or high-risk warnings.', related: ['Read freezing', './signals.html?signal=freeze'] }
});

const signalSearchStopWords = new Set(['a', 'about', 'always', 'am', 'an', 'and', 'are', 'as', 'be', 'because', 'did', 'does', 'dont', 'for', 'from', 'how', 'i', 'if', 'in', 'is', 'it', 'its', 'know', 'me', 'mean', 'means', 'my', 'of', 'on', 'or', 'so', 'the', 'their', 'them', 'they', 'theyre', 'to', 'was', 'what', 'when', 'why', 'will', 'with', 'you', 'your']);
function signalQueryTerms(value) {
  return String(value ?? '').toLowerCase().replace(/[’']/g, '').match(/[a-z0-9]+/g)?.filter((word) => word.length > 1 && !signalSearchStopWords.has(word)) || [];
}
function signalSearchMatches(key, signal, query) {
  const terms = signalQueryTerms(query);
  if (!terms.length) return !query.trim();
  const searchable = signalQueryTerms(`${key} ${signal.category} ${signal.title} ${signal.summary} ${signal.see} ${signal.check} ${signal.meaning} ${signal.avoid} ${(signal.searchTerms || []).join(' ')}`);
  return terms.every((term) => searchable.some((word) => word.includes(term) || term.includes(word)));
}

const categories = ['All', 'Face', 'Ears', 'Mouth', 'Tail', 'Body', 'Movement', 'Warnings'];
const grid = document.getElementById('signal-grid');
const filters = document.getElementById('signal-filters');
const search = document.getElementById('signal-search');
const count = document.getElementById('signal-count');
const kicker = document.getElementById('read-kicker');
const title = document.getElementById('read-title');
const summary = document.getElementById('read-summary');
const readImage = document.getElementById('read-image');
const list = document.getElementById('read-list');
const related = document.getElementById('read-related');
let activeCategory = 'All';
let activeKey = 'soft-eyes';
const dialog = document.getElementById('signal-dialog');
const clearFilters = document.getElementById('signal-clear');
const previous = document.getElementById('signal-prev');
const next = document.getElementById('signal-next');
const pageLabel = document.getElementById('signal-page');
const pageSize = 8;
let pageIndex = 0;

function renderFilters() {
  filters.innerHTML = categories.map((category) => `<button class="filter-button" type="button" aria-pressed="${String(activeCategory === category)}" data-category="${category}">${category}</button>`).join('');
  filters.querySelectorAll('[data-category]').forEach((button) => button.addEventListener('click', () => {
    activeCategory = button.dataset.category;
    pageIndex = 0;
    filters.querySelectorAll('button').forEach((item) => item.setAttribute('aria-pressed', String(item === button)));
    renderCards();
  }));
}

function renderCards() {
  const query = search.value.trim().toLowerCase();
  const entries = Object.entries(signalContent).filter(([key, signal]) => {
    const matchesCategory = activeCategory === 'All' || signal.category === activeCategory;
    return matchesCategory && signalSearchMatches(key, signal, query);
  });
  const pageCount = Math.max(1, Math.ceil(entries.length / pageSize));
  pageIndex = Math.min(pageIndex, pageCount - 1);
  const visible = entries.slice(pageIndex * pageSize, (pageIndex + 1) * pageSize);
  count.textContent = entries.length ? `Showing ${pageIndex * pageSize + 1}–${pageIndex * pageSize + visible.length} of ${entries.length} clues` : 'No matching clues';
  pageLabel.textContent = `Page ${pageIndex + 1} of ${pageCount}`;
  previous.disabled = pageIndex === 0; next.disabled = pageIndex === pageCount - 1;
  previous.parentElement.hidden = pageCount === 1;
  clearFilters.hidden = !query && activeCategory === 'All';
  grid.innerHTML = visible.length ? visible.map(([key, signal], index) => `<button class="signal-card" type="button" aria-haspopup="dialog" aria-controls="signal-dialog" data-signal="${key}"><img class="signal-thumb" src="${signal.image}" alt="" width="768" height="768" loading="${index < 4 ? 'eager' : 'lazy'}" decoding="async" /><span class="signal-card-copy"><span class="signal-category">${signal.category}</span><span class="signal-card-title">${signal.title}</span><span class="signal-card-summary">${signal.summary}</span></span></button>`).join('') : '<div class="empty-state"><h2>No matching clue.</h2><p>Try “tail,” “ears,” “licking,” “freeze,” “play,” or “growl,” or clear your filters.</p></div>';
  grid.querySelectorAll('[data-signal]').forEach((card) => card.addEventListener('click', () => selectSignal(card.dataset.signal)));
}

function selectSignal(key) {
  const signal = signalContent[key] || signalContent['soft-eyes'];
  activeKey = key;
  kicker.textContent = signal.kicker;
  title.textContent = signal.title;
  summary.textContent = signal.summary;
  readImage.src = signal.image;
  readImage.alt = signal.alt;
  list.innerHTML = [['What you might see', signal.see], ['Check with it', signal.check], ['What it may mean', signal.meaning], ['Don’t assume', signal.avoid], ['Kind response', signal.response], ['Get support if', signal.help]].map(([label, copy]) => `<li><strong>${label}</strong><span>${copy}</span></li>`).join('');
  related.innerHTML = signal.related ? `<a class="text-link" href="${signal.related[1]}">${signal.related[0]} →</a>` : '';
  document.dispatchEvent(new Event('wagsignals:stop-audio'));
  const url = new URL(window.location.href); url.searchParams.set('signal', activeKey);
  history.replaceState(null, '', url);
  if (!dialog.open) dialog.showModal();
  dialog.scrollTop = 0;
}

document.getElementById('signal-close').addEventListener('click', () => dialog.close());
dialog.addEventListener('click', (event) => { if (event.target === dialog) { const box = dialog.getBoundingClientRect(); if (event.clientX < box.left || event.clientX > box.right || event.clientY < box.top || event.clientY > box.bottom) dialog.close(); } });
dialog.addEventListener('close', () => {
  document.dispatchEvent(new Event('wagsignals:stop-audio'));
  const url = new URL(window.location.href); url.searchParams.delete('signal'); history.replaceState(null, '', url);
  const card = grid.querySelector(`[data-signal="${activeKey}"]`);
  (card || search).focus({ preventScroll: true });
});
clearFilters.addEventListener('click', () => { search.value = ''; activeCategory = 'All'; pageIndex = 0; renderFilters(); renderCards(); search.focus(); });
previous.addEventListener('click', () => { pageIndex -= 1; renderCards(); count.focus(); });
next.addEventListener('click', () => { pageIndex += 1; renderCards(); count.focus(); });
search.addEventListener('input', () => { pageIndex = 0; renderCards(); });
renderFilters();
renderCards();
const requested = new URLSearchParams(window.location.search).get('signal');
if (requested && signalContent[requested]) selectSignal(requested);
