/* WagSignals lesson content: practical, reward-based guidance, authored for this site. */
window.WagSignalsTrainingLessons = [
  {
    id: 'loose-leash', order: '06', category: 'Walks & movement', title: 'Loose-leash walking',
    summary: 'Help your dog explore beside you while the leash stays comfortably slack.',
    image: './assets/training-leash.webp', alt: 'A dog walking beside a handler on a loose leash with a visible slack curve',
    overview: [
      'Loose-leash walking means the leash has a soft curve while your dog can move, sniff, and check in. It is not a heel or a demand to stay glued to your leg.',
      'The useful everyday goal is a safer, more comfortable walk with fewer moments of steady pulling. Progress depends on the dog, surroundings, and practice—not a guaranteed timetable.'
    ],
    setup: [
      ['Choose a setting', 'Begin indoors, in a yard, or on a quiet path where your dog can notice you without being overwhelmed.'],
      ['Use comfortable gear', 'Fit a secure, comfortable harness or flat collar and a standard leash. Check fit before each walk; never jerk or tighten it to teach.'],
      ['Bring rewards', 'Use small food rewards your dog enjoys. Sniffing and moving forward can also be part of the reward.'],
      ['Keep it easy', 'Plan a few short practice stretches inside a normal walk, with rest and sniff breaks between them.']
    ],
    stages: [
      { title: 'Find an easy starting position', do: 'Stand still in a quiet place. Let your dog settle beside you or turn toward you; do not hold food at their nose to keep them there.', watch: 'Look for a loose body, a leash that hangs in a curve, or a voluntary glance back.', reward: 'Mark that moment with “yes” and offer a small reward close to your leg, then let your dog move away again.', repeat: 'Repeat a few times, pausing if your dog gets restless or stops taking food.', ready: 'Move on when your dog can choose to return near you and the leash stays slack for several easy repetitions.' },
      { title: 'Add one or two steps', do: 'Take a single step, then another, at your dog’s pace. Keep the leash hand soft and follow a safe direction your dog can manage.', watch: 'Notice whether the leash still curves and your dog can sniff or glance back without being tugged.', reward: 'Mark slack and voluntary check-ins. Feed near you, or allow a short sniff when it is safe.', repeat: 'If the leash tightens, stop only where it is safe to do so. Wait quietly for slack or invite your dog back with a cheerful cue; then restart easier.', ready: 'Add a few more steps after several calm, slack-leash starts—not after one lucky pass.' },
      { title: 'Practice in a quiet outdoor place', do: 'Try a short section of a familiar, low-distraction route. Give your dog room to move and explore without crossing into hazards.', watch: 'Your dog should still be able to notice you, sniff, and recover after ordinary sights or sounds.', reward: 'Reward the slack leash and any voluntary return toward you. Let safe sniffing continue as a meaningful part of the walk.', repeat: 'If pulling builds, make a safe turn away or pause in a protected spot; do not drag your dog back toward you.', ready: 'Try a slightly busier place only when the quieter route remains comfortable on repeated outings.' },
      { title: 'Build a real-life walking rhythm', do: 'Alternate short stretches of connection with “go sniff” breaks in safe areas. Practice near mild distractions at a distance your dog can handle.', watch: 'Look for a leash that softens again quickly and a dog able to disengage from distractions.', reward: 'Keep rewarding good choices intermittently, especially near new distractions. Sniffing can be the reward when food is less useful.', repeat: 'If the walk becomes tense, increase distance or return to a quieter route for the rest of that outing.', ready: 'Increase only one challenge at a time: route busyness, walking duration, or proximity to a distraction.' }
    ],
    success: ['The leash has a visible soft curve for much of an easy practice stretch.', 'Your dog can sniff, look around, and sometimes choose to reconnect without being pulled.', 'After a mild distraction, your dog can soften and continue or take a break.'],
    struggles: [
      ['The leash stays tight', 'Lower the difficulty: pause in a safe spot, add distance from what your dog wants to reach, and reward nearer to you before moving again.'],
      ['Your dog cannot take a reward or look back', 'The setting may be too intense. Leave the area calmly, choose a quieter route, and let your dog decompress.'],
      ['Stopping makes the situation less safe', 'Do not plant your feet in traffic or a crowd. Move to the nearest safe space first; management comes before practice.']
    ],
    mistakes: [
      ['Expecting a heel for the whole walk', 'Aim for a comfortable slack leash, not a fixed position. Give room for sniffing and natural movement.'],
      ['Practicing only when the dog is already pulling hard', 'Start before the leash tightens, in an easier place where your dog can succeed.'],
      ['Changing direction sharply or correcting the leash', 'Use a gentle, planned turn only where safe. Do not yank, drag, or use discomfort as a shortcut.']
    ],
    safety: 'Keep your dog securely attached near roads, bikes, wildlife, and unfamiliar dogs. If walking causes pain, panic, repeated lunging, or you cannot hold your dog safely, stop this exercise and ask your veterinarian or a qualified reward-based behavior professional for an individual plan.',
    next: 'Keep some walks easy. When your dog is comfortable on one route, practice the same small skill in one new place at a time. A longer walk is not automatically a better training session.',
    sources: [{ label: 'Dogs Trust: walking nicely on a lead', href: 'https://www.dogstrust.org.uk/dog-advice/training/outdoors/walking-nicely-training' }]
  },
  {
    id: 'leave-it', order: '07', category: 'Everyday safety', title: 'Leave it',
    summary: 'Teach your dog to turn away from an item before they get it.',
    image: './assets/training-leave-it.webp', alt: 'A dog looking away from a treat in a handler’s hand',
    overview: [
      '“Leave it” is a choice to disengage before your dog takes or reaches an item. It is different from “drop it,” which asks for something already in the mouth to be released.',
      'Practice builds a useful cue, but it cannot make an unsafe object safe or replace supervision, barriers, and picking hazards up.'
    ],
    setup: [
      ['Choose a safe practice item', 'Use a low-value piece of ordinary dog food or another safe item your dog does not guard. Keep dangerous food, medicine, and rubbish out of the exercise.'],
      ['Prepare a second reward', 'Have a few better rewards in your other hand so you can reward disengaging without giving the practice item.'],
      ['Start in a calm room', 'Sit or stand comfortably, with space for your dog to turn away. Keep hands low and still.'],
      ['Keep the first tries easy', 'Work for a few brief choices, then stop while your dog is still comfortable.']
    ],
    stages: [
      { title: 'Reward moving away from a closed hand', do: 'Put one low-value treat in a closed fist and offer the fist calmly. Do not say the cue or push the hand toward your dog.', watch: 'Wait for any small pause, nose movement away, or head turn. Do not wait for a perfect sit or eye contact.', reward: 'Mark the instant your dog moves away, then feed a different reward from your other hand.', repeat: 'If your dog keeps mouthing or pawing, stay quiet and keep your fist closed. Pause or make it easier if your dog becomes frustrated.', ready: 'Continue when your dog repeatedly chooses to move away within a short, relaxed practice.' },
      { title: 'Add the cue to a familiar choice', do: 'When the turn-away is predictable, say “leave it” once just before you present the closed hand. Keep the hand still.', watch: 'Look for your dog to pause or turn away after the cue, rather than rush the fist.', reward: 'Mark the disengagement and reward from the other hand every time during early learning.', repeat: 'If your dog reaches for the fist, close your hand and wait; do not repeat the cue. Return to the easier setup if needed.', ready: 'Make the hand slightly easier to see only after your dog can respond calmly to the cue in repeated trials.' },
      { title: 'Make the safe item easier to see', do: 'Show a safe, low-value treat on an open palm briefly. If your dog leans in, calmly close your hand before they can take it.', watch: 'Notice whether your dog can turn away or wait without lunging, freezing, or becoming frustrated.', reward: 'Mark a choice to disengage and give a better reward from your other hand, away from the practice item.', repeat: 'Keep the item covered between tries. If your dog struggles, go back to the closed fist.', ready: 'Progress when your dog can turn away reliably in this calm setup; do not jump straight to hazards on the floor.' },
      { title: 'Practice with a protected floor item', do: 'Place a safe practice treat on the floor under your shoe or a small cover, with your dog on a comfortable leash only if needed for safety.', watch: 'Look for a pause, head turn, or check-in while the item stays protected.', reward: 'Mark disengaging and reward from your hand, then move away together.', repeat: 'Cover the item immediately if your dog moves toward it. Keep distance and supervision; never use a dangerous object as a test.', ready: 'Generalize to another safe item and calm place one at a time. Keep management in place in real life.' }
    ],
    success: ['Your dog can disengage from the safe practice item without being physically moved.', 'The cue predicts a chance to turn away and earn a separate reward.', 'Your dog remains relaxed enough to pause, sniff, and try again.'],
    struggles: [
      ['Your dog keeps nosing or pawing the fist', 'Do not scold or repeat the cue. Stay still briefly; if frustration rises, end the try and restart later with a lower-value item or more space.'],
      ['Your dog grabs the open-hand treat', 'Close the hand calmly and return to an easier step. Make the reward for turning away better and keep the practice item protected.'],
      ['Your dog guards food or becomes worried', 'Stop hand-based practice. Give space and ask a qualified reward-based behavior professional for a plan; do not test or take guarded items.']
    ],
    mistakes: [
      ['Saying “leave it” again and again', 'Give the cue once at a level your dog understands, then help by covering or moving away from the item.'],
      ['Rewarding with the item you asked them to leave', 'Use a different reward so turning away remains the choice that pays.'],
      ['Trying this first on rubbish, medication, or a dangerous find', 'Secure hazards and supervise. In an urgent situation, use a barrier and seek veterinary advice instead of testing a new cue.']
    ],
    safety: 'Store medicines, toxic foods, sharp objects, and rubbish out of reach. A trained cue is not guaranteed in an emergency. If your dog has swallowed something potentially harmful, contact a veterinarian or animal poison service promptly; do not induce vomiting unless a veterinary professional instructs you.',
    next: 'Practice the cue with a few different safe objects and quiet rooms. Keep real hazards physically unavailable, and use a well-practiced trade if your dog already has an item.',
    sources: [{ label: 'RSPCA: teaching your dog to leave something alone', href: 'https://www.rspca.org.uk/adviceandwelfare/pets/dogs/training/leave' }]
  },
  {
    id: 'drop-it', order: '08', category: 'Everyday safety', title: 'Drop it',
    summary: 'Teach a voluntary, reward-based release of a safe toy already in your dog’s mouth.',
    image: './assets/training-rewards.webp', alt: 'A dog sitting calmly while its handler offers a reward near a toy',
    overview: [
      '“Drop it” asks your dog to let go of something they already hold. It is not the same as “leave it,” which is for turning away before taking an item.',
      'The goal is a relaxed release because a fair exchange is worthwhile—not a forced mouth opening. Start with a safe, low-value toy, not a dangerous object.'
    ],
    setup: [
      ['Choose the right toy', 'Use a safe toy your dog likes but can readily leave. Avoid tiny, splintering, or easily swallowed objects.'],
      ['Prepare an exchange', 'Have a second safe toy your dog enjoys ready. A treat may be an alternative reward if your dog is comfortable taking one.'],
      ['Choose a calm space', 'Begin at home with enough room to stand sideways and avoid looming over your dog.'],
      ['Keep play easy', 'Use a few brief trades. Stop if your dog stiffens, freezes, guards, or becomes overexcited.']
    ],
    stages: [
      { title: 'Trade one safe toy for another', do: 'Let your dog hold a safe, easy-to-leave toy. From a comfortable distance, invite them to take interest in a second toy; do not reach toward the first.', watch: 'Notice whether your dog voluntarily releases the first toy and stays loose while moving to the second.', reward: 'Mark the release as it happens, then give your dog a brief, enjoyable turn with the second toy.', repeat: 'Let your dog move away between trades. If the second toy is not interesting, stop and try an easier pairing another time.', ready: 'Continue when your dog can release this familiar toy calmly in several short, low-pressure trades.' },
      { title: 'Pair the word with a familiar release', do: 'When you can predict your dog is about to let go to take the second toy, say “drop it” gently as the release happens.', watch: 'The word should accompany a release your dog already chooses; it is not a command to pry or pressure.', reward: 'Offer the second toy promptly and resume play if the dog remains comfortable.', repeat: 'If the cue makes your dog hesitate or hold tighter, stop using the word and return to uncued exchanges.', ready: 'Continue when the cue can be said once without changing the dog’s relaxed choice to release.' },
      { title: 'Invite the release with one cue', do: 'During easy play, say “drop it” once, then present the second toy at a comfortable distance. Give your dog time to choose.', watch: 'Look for the familiar, voluntary release and loose posture. Do not lean over, grab, or repeat the cue.', reward: 'Mark the release, then let your dog play briefly with the second toy. Return the first toy when safe.', repeat: 'If your dog does not release, calmly put the second toy away and make the next practice easier. Do not turn it into a chase.', ready: 'Continue when your dog responds calmly with this familiar toy across separate short sessions.' },
      { title: 'Generalize to other safe toys', do: 'Try a different low-value safe toy in another quiet setting. Keep the second toy appealing, and change only one detail at a time.', watch: 'A new object may feel more valuable; watch for tension, stillness, or a dog moving away to protect it.', reward: 'Mark a relaxed release and make the exchange enjoyable; return the item when safe.', repeat: 'If your dog holds on or guards, stop. Do not practice on bones, stolen food, medicines, or other hazards.', ready: 'Keep using physical management for real hazards; a learned cue is never a guarantee in an emergency.' }
    ],
    success: ['Your dog releases a familiar, safe toy without anyone touching their mouth or pulling the object.', 'Your dog stays loose and is willing to re-engage after the trade.', 'The cue is followed by a reward often enough to keep the exchange predictable.'],
    struggles: [
      ['Your dog will not leave the toy', 'Use a less valuable toy, toss a better treat farther away, and give your dog more room. Return to uncued trades if the word has lost meaning.'],
      ['Your dog runs away with the object', 'Do not chase. Make the area safe, turn slightly sideways, and offer a better trade from a distance. Prevent access to tempting unsafe items.'],
      ['Your dog freezes, growls, or guards', 'End the exercise and give space. Do not reach, scold, or take the item; seek an individualized plan from a qualified reward-based behavior professional and your veterinarian.']
    ],
    mistakes: [
      ['Trying to pry the mouth open or pull the object away', 'Use a trade and keep hands away from the mouth. Force can cause injury and make guarding worse.'],
      ['Always taking the toy and ending play', 'When safe, give the toy back or start another game after the release.'],
      ['Practicing first with a dangerous object', 'Teach with safe toys before any real-life emergency. For a swallowed toxin or object, contact a veterinarian promptly rather than relying on a cue.']
    ],
    safety: 'Never practice by putting fingers in your dog’s mouth. For guarding or a bite risk, stop and get professional help. If your dog may have swallowed a toxic or obstructive object, contact a veterinarian or animal poison service urgently; do not induce vomiting unless a veterinary professional tells you to.',
    next: 'Keep the skill easy and rewarding. Later, vary safe toys and rooms gradually, while continuing to prevent access to dangerous items.',
    sources: [
      { label: 'Dogs Trust: resource guarding in dogs', href: 'https://www.dogstrust.org.uk/dog-advice/training/unwanted-behaviours/resource-guarding-food-and-toys' },
      { label: 'AVSAB: reward-based training position statements', href: 'https://avsab.org/resources/position-statements/' }
    ]
  },
  {
    id: 'name-attention', order: '01', category: 'Everyday cues', title: 'Name & attention',
    summary: 'Make your dog’s name a friendly invitation to check in—not a command to stare.',
    image: './assets/training-attention.webp', alt: 'A dog turning toward a handler after hearing its name',
    overview: ['A name can become a simple cue that predicts something pleasant and helps your dog orient toward you. Looking at your face is not required; a head turn or ear flick can be a good first response.', 'This exercise builds a small connection skill. It does not replace recall, a leash, or a safe barrier.'],
    setup: [['Setting', 'Choose a familiar, quiet room with your dog nearby and free to move away.'], ['Reward', 'Prepare a few small treats or another reward your dog enjoys.'], ['Timing', 'Wait until your dog is not already looking at you, but is calm enough to hear.'], ['Session', 'Practice a handful of easy turns, then take a break. Stop sooner if your dog disengages.']],
    stages: [
      { title: 'Reward noticing the name', do: 'Say your dog’s name once in a warm, ordinary voice. Keep your body relaxed and do not wave food in front of their nose.', watch: 'Notice any ear turn, head turn, or brief orientation toward you.', reward: 'Mark the turn with “yes,” then offer the reward. Let your dog look away before another try.', repeat: 'If there is no response, wait a few seconds and make the next try easier; do not repeat louder.', ready: 'Continue when your dog responds comfortably to the single cue across several short tries.' },
      { title: 'Build a relaxed check-in', do: 'Pause between repetitions and say the name when your dog is calmly occupied nearby.', watch: 'Look for a willing turn without startle, tension, or needing to see food first.', reward: 'Reward the turn, then allow your dog to return to what they were doing.', repeat: 'Keep the reward hidden until after the turn so the name—not a visible lure—starts the behavior.', ready: 'Move to a slightly different room when the name predicts a pleasant check-in in this one.' },
      { title: 'Change one easy detail', do: 'Practice in one new room or with you a short step farther away. Change only one of those things at a time.', watch: 'Your dog should still be able to hear and respond without stopping in worry.', reward: 'Mark the first small orientation and reward where your dog can comfortably reach you.', repeat: 'If your dog misses the cue, reduce the distance or return to the familiar room.', ready: 'Try a mildly busier setting only after the easier version stays comfortable.' },
      { title: 'Use it in everyday moments', do: 'Try the name indoors or in a secure, low-distraction place when your dog can safely turn toward you.', watch: 'Notice whether the dog can turn and then choose to continue exploring.', reward: 'Pay check-ins with food, play, praise, or permission to return to sniffing.', repeat: 'Keep higher distractions for later. If you need immediate control, use the leash or barrier instead of repeating the name.', ready: 'Keep refreshing the cue in easy contexts; it is fine if responses vary with attention and surroundings.' }
    ],
    success: ['Your dog turns an ear, head, or body toward you after one calm cue in an easy setting.', 'The dog stays relaxed and can return to their activity after the reward.', 'A missed response leads you to adjust the setup, not to call louder.'],
    struggles: [['No response', 'Check that your dog can hear you, move closer, and reduce competing sights or sounds.'], ['Dog only responds when food is visible', 'Hide the reward until after the turn, and practice at an easier distance.'], ['Dog looks worried when called', 'Use a softer voice, give more space, and avoid pairing the name with scolding or unwanted handling.']],
    mistakes: [['Repeating the name rapidly', 'Say it once, then wait. Repeating can make the cue fade into background noise.'], ['Expecting eye contact', 'Reward a comfortable orientation; looking away is also normal dog communication.'], ['Using the name only to end fun', 'Sometimes reward and let the dog return to a safe activity.']],
    safety: 'Use a secure leash and barriers around roads, open doors, wildlife, or unfamiliar dogs. A name response is not a reliable emergency recall. A sudden change in response to sound can warrant a veterinary hearing or health check.',
    next: 'Keep the name cheerful and useful. When it works in an easy room, use it once to invite a check-in before another familiar reward-based activity.',
    sources: [{ label: 'AVSAB: reward-based training position statements', href: 'https://avsab.org/resources/position-statements/' }]
  },
  {
    id: 'sit', order: '02', category: 'Everyday cues', title: 'Sit',
    summary: 'Teach a comfortable sit by rewarding the movement, then add a clear cue and release.',
    image: './assets/training-sit-wait.webp', alt: 'A dog sitting on a mat while a handler offers a calm hand cue',
    overview: ['A sit is a useful position for short pauses, but it should be comfortable and optional—not a way to hold a dog in place.', 'Reward the action you want. Do not push on your dog’s back or keep them sitting when they need to move.'],
    setup: [['Surface', 'Choose a quiet, non-slip floor or mat with room to stand and turn.'], ['Reward', 'Have small treats ready; use food only if your dog is comfortable taking it.'], ['Position', 'Stand or sit close enough to reward without leaning over your dog.'], ['Plan', 'Keep each practice short and end with a clear release such as “all done.”']],
    stages: [
      { title: 'Notice a natural sit', do: 'Wait calmly in a familiar room and watch for your dog to sit on their own.', watch: 'Look for a balanced, comfortable sit rather than a crouch or painful shift.', reward: 'Mark as the bottom reaches the floor and reward beside the dog, then invite them to move.', repeat: 'Allow a reset between sits; do not lure continuously or hold your dog in place.', ready: 'Practice a few times when your dog can choose to sit and stand comfortably.' },
      { title: 'Help the movement if useful', do: 'If your dog is comfortable with food, hold a treat near the nose and move it slowly just upward and slightly back. Stop if they step away.', watch: 'Watch for the bottom lowering naturally; reward a small comfortable bend if a full sit is difficult.', reward: 'Mark the movement and deliver the treat as soon as the sit happens.', repeat: 'After the reward, let your dog stand and reset. Do not press down on their back.', ready: 'Use less visible food as the movement becomes predictable.' },
      { title: 'Add the word', do: 'When your dog is already beginning to sit reliably, say “sit” once just before the familiar movement or hand signal.', watch: 'Give the dog time to respond; avoid repeating the word or adding pressure.', reward: 'Mark and reward a comfortable sit, then release.', repeat: 'If your dog does not sit, make the hand signal easier or return to rewarding the natural movement.', ready: 'Continue after the cue predicts the movement in this quiet setting across several tries.' },
      { title: 'Use it in a few calm routines', do: 'Practice near a familiar doorway or before setting down a toy, away from traffic and crowding.', watch: 'Notice whether your dog can sit briefly and rise freely without discomfort.', reward: 'Reward the sit, then use the release cue so the dog knows the pause has ended.', repeat: 'If a greeting or environment makes sitting difficult, increase space and let the dog stand.', ready: 'Add a new room or mild distraction only when the dog remains comfortable.' }
    ],
    success: ['Your dog lowers into a balanced sit without physical pressure.', 'The dog can stand again promptly when released.', 'The cue works in a quiet context without repeated prompting.'],
    struggles: [['Your dog steps backward from the lure', 'Move the treat less, reward a smaller bend, or capture a natural sit instead.'], ['The floor is slippery', 'Move to a non-slip mat and make the movement smaller.'], ['The sit looks stiff, uneven, or painful', 'Stop and ask your veterinarian about discomfort before training the position.']],
    mistakes: [['Pushing the dog into position', 'Allow the movement to happen by choice and reward it.'], ['Repeating the cue', 'Say it once when the dog is ready; if it fails, simplify the setup.'], ['Expecting long stillness', 'Keep sits brief and release. Teach a separate settle if you want voluntary rest.']],
    safety: 'Avoid repeated sits if your dog shows stiffness, pain, weakness, or difficulty standing. Ask your veterinarian before practicing if movement is uncomfortable. A sit is never a safety barrier at an open door or near traffic.',
    next: 'Practice the same short cue in one more calm room. Keep rewarding the choice and releasing promptly; increase only one distraction at a time.',
    sources: [{ label: 'AVSAB: reward-based training position statements', href: 'https://avsab.org/resources/position-statements/' }]
  },
  {
    id: 'down', order: '03', category: 'Everyday cues', title: 'Down',
    summary: 'Reward your dog for choosing a comfortable lie-down, then add the cue gradually.',
    image: './assets/training-settle.webp', alt: 'A dog resting on a mat beside a seated handler',
    overview: ['“Down” asks for a lying position. It is different from “settle,” which is a relaxed choice to rest.', 'Let your dog find the position without pulling legs or pressing shoulders. A lie-down may be uncomfortable for some dogs.'],
    setup: [['Surface', 'Use a comfortable, non-slip mat or rug in a quiet room.'], ['Rewards', 'Prepare a few small treats that can be delivered low to the floor.'], ['Starting position', 'Begin when your dog is calm and can stand or sit comfortably.'], ['Session', 'Practice a few easy movements with a chance to stand and reset between them.']],
    stages: [
      { title: 'Reward a natural lowering movement', do: 'Wait for your dog to lower their elbows or choose to lie down on the mat.', watch: 'Notice whether the movement is smooth and balanced; do not insist on a full down if it looks awkward.', reward: 'Mark the comfortable lowering and place the reward near the paws.', repeat: 'Allow your dog to stand or move away after the treat.', ready: 'Continue once your dog can choose a comfortable lowering movement in this familiar spot.' },
      { title: 'Guide the movement gently', do: 'If your dog is comfortable following food, move a treat from the nose slowly toward the floor between the front paws. Keep the hand close to the body.', watch: 'Look for elbows bending or the chest lowering. If your dog backs away, stop and make the lure smaller.', reward: 'Mark and reward a comfortable bend or full lie-down.', repeat: 'Reset between tries and let the dog stand; do not trap them in the position.', ready: 'Use the same smooth hand motion only while the dog continues to follow it willingly.' },
      { title: 'Pair the word with the movement', do: 'When the lowering motion is familiar, say “down” once just before your hand signal.', watch: 'Give a pause for the dog to respond; do not push them to finish.', reward: 'Mark the movement and reward on the mat, then release.', repeat: 'If the dog hesitates, return to the easier hand signal or reward a natural lie-down.', ready: 'Move to a new quiet room after the cue predicts the comfortable movement here.' },
      { title: 'Practice in short everyday moments', do: 'Ask for a brief down on a familiar comfortable surface, then release before your dog becomes restless.', watch: 'Check that the body remains loose and the dog can rise smoothly.', reward: 'Reward promptly and give the release cue.', repeat: 'If the surface or setting is distracting, return to the quiet mat.', ready: 'Add only a mildly busier setting when your dog stays comfortable and can rise freely.' }
    ],
    success: ['Your dog lowers into a lie-down smoothly on a comfortable surface.', 'The dog remains relaxed and stands without difficulty after release.', 'A small step or natural lie-down is accepted as progress.'],
    struggles: [['Your dog backs away from your hand', 'Stop luring. Reward a natural lowering movement or make the hand motion smaller.'], ['Your dog lies down only on a soft surface', 'That may be a comfort preference; keep a soft mat available rather than insisting on hard floors.'], ['Your dog avoids lying down or rises stiffly', 'Stop practice and ask your veterinarian about pain or mobility.']],
    mistakes: [['Pushing shoulders or pulling legs', 'Never physically place the dog. Make the surface and lure more comfortable.'], ['Confusing a short down cue with a long settle', 'Release promptly; teach relaxed resting as a separate, voluntary skill.'], ['Repeating “down” while the dog is moving', 'Use the cue once at an easy level, then pause or reset.']],
    safety: 'Do not practice this position through stiffness, soreness, injury, or reluctance. Stop and consult your veterinarian if lying down or getting up looks uncomfortable. Never use “down” to pin a worried dog in place.',
    next: 'Once the cue is easy on one mat, practice in another comfortable place. Keep the position brief and let your dog choose to stand when released.',
    sources: [{ label: 'AVSAB: reward-based training position statements', href: 'https://avsab.org/resources/position-statements/' }]
  },
  {
    id: 'stay-wait', order: '04', category: 'Everyday cues', title: 'Stay & wait',
    summary: 'Build a brief, calm pause by rewarding before your dog needs to move.',
    image: './assets/training-sit-wait.webp', alt: 'A dog calmly waiting on a mat while a handler stands nearby',
    overview: ['A stay is a short pause in a position; a wait is often a brief pause before moving on. Use a release word so your dog knows when the pause is over.', 'Teach this as a small, easy choice. A stay is never a substitute for a gate, leash, or adult supervision.'],
    setup: [['Start with a familiar position', 'Use a comfortable sit or down your dog already knows, on a non-slip surface.'], ['Choose a quiet place', 'Practice away from doors, stairs, roads, food, and exciting visitors.'], ['Prepare rewards', 'Have treats ready so you can reward while staying close.'], ['Plan the release', 'Pick one clear word such as “okay” or “all done,” and use it consistently.']],
    stages: [
      { title: 'Pause for one easy moment', do: 'Ask for a familiar sit or down, say “stay” once, and pause for about a beat.', watch: 'Look for a loose body and the dog remaining in place by choice.', reward: 'Reward while you are still beside the dog, then give the release word.', repeat: 'If the dog moves, calmly reset without correction and make the pause shorter.', ready: 'Continue when the dog can pause briefly and release calmly several times.' },
      { title: 'Add a little time', do: 'After the cue, wait just slightly longer before returning the reward. Keep your feet close.', watch: 'Notice weight shifts, lip licking, scanning, or the dog starting to rise; these can mean the step is too hard.', reward: 'Return and reward before the dog feels they have to break position, then release.', repeat: 'If the dog gets up, reduce the pause. Do not repeat “stay” more loudly.', ready: 'Add a small amount of duration only after the current pause remains easy.' },
      { title: 'Add a small movement', do: 'Take one small step to the side or back, immediately return, reward, and release.', watch: 'Check whether your movement changes the dog’s comfort or causes them to follow.', reward: 'Reward close to the dog while they are still in position.', repeat: 'If they follow, make your movement smaller or stay in place for more practice.', ready: 'Try a slightly bigger movement only after several relaxed repetitions.' },
      { title: 'Use a brief pause in a safe routine', do: 'Practice waiting while you pick up a toy or prepare a meal, with a barrier or leash still managing access.', watch: 'Keep the pause short enough that your dog can stay relaxed.', reward: 'Release and reward before moving to the next part of the routine.', repeat: 'If the door or food makes the dog rush, increase distance and use a physical barrier.', ready: 'Generalize to a new room by changing just one element, never by testing near a hazard.' }
    ],
    success: ['Your dog can hold a brief pause without a tense or frozen body.', 'You return to reward close by, then release clearly.', 'The dog can make a mistake and restart without pressure.'],
    struggles: [['Your dog gets up right away', 'Shorten the pause and reward sooner, while staying close.'], ['Your dog follows your step', 'Move less—perhaps shift your weight before taking a full step.'], ['Your dog becomes tense near a door', 'Use a gate or closed door for safety and practice farther away from the exit.']],
    mistakes: [['Increasing time, distance, and distraction together', 'Change only one element in an easy practice.'], ['Calling the dog out of a stay before rewarding', 'Return to the dog and reward in place, then give the release cue.'], ['Using stay to hold the dog near danger', 'Use secure management instead; training is not an emergency barrier.']],
    safety: 'Keep dogs behind a secure barrier or on a leash near doors, roads, stairs, children, and unfamiliar animals. Do not ask a fearful or painful dog to stay in place while a trigger approaches.',
    next: 'Keep the pause short and useful. Add one second or one small step at a time, and return to an easier version whenever your dog struggles.',
    sources: [{ label: 'Dogs Trust: stay training', href: 'https://www.dogstrust.org.uk/dog-advice/training/basics/stay-training' }]
  },
  {
    id: 'come', order: '05', category: 'Everyday cues', title: 'Come when called',
    summary: 'Make returning to you rewarding, and keep the dog safely attached while learning.',
    image: './assets/training-recall.webp', alt: 'A dog running happily toward a handler in a safe fenced field',
    overview: ['Recall asks your dog to turn and come close when called. Build it in easy places so returning predicts something good.', 'No recall is guaranteed in every emergency. Use a secure leash and enclosed areas while the skill is developing.'],
    setup: [['Start nearby', 'Choose a calm room with only a few steps between you and your dog.'], ['Prepare a generous reward', 'Use several treats, a favorite toy, or brief play—something your dog truly enjoys.'], ['Keep the cue fresh', 'Use one clear word or happy sound, and avoid using it when you cannot reward or manage the dog.'], ['Plan to release', 'Have a safe activity ready so not every return ends the fun.']],
    stages: [
      { title: 'Practice a close, easy return', do: 'When your dog is a few steps away and not deeply distracted, say the recall cue once in a cheerful voice. You can crouch or move back a step.', watch: 'Look for a turn toward you and approach; accept a quick first step as progress.', reward: 'Mark when your dog reaches you and offer several small rewards or a favorite brief game.', repeat: 'Let the dog reset between attempts. Do not chase or call repeatedly.', ready: 'Repeat until your dog turns and comes close easily in this quiet room.' },
      { title: 'Add a little distance', do: 'Call from a few more steps away in the same safe room or fenced area.', watch: 'Your dog should still be able to disengage from what they are doing.', reward: 'Reward generously at your side, then release them back to exploring when safe.', repeat: 'If they hesitate, move closer and make the next call easier.', ready: 'Try a new room after a relaxed return is common at the current distance.' },
      { title: 'Practice with a secure long line', do: 'In a quiet outdoor area, use a well-fitted harness and a long line attached securely. Let the dog explore before calling at an easy moment.', watch: 'Notice whether they can turn away from sniffing or a mild distraction.', reward: 'Reward the return generously, then release back to sniffing if the area is safe.', repeat: 'If the line tightens, do not reel the dog in as training. Reduce distance and call when success is likely.', ready: 'Increase distraction only when the earlier outdoor setup remains safe and easy.' },
      { title: 'Keep recall valuable in daily life', do: 'Call once in situations where you can reward and safely manage the outcome.', watch: 'If your dog cannot respond, the environment is too difficult or the moment is poorly timed.', reward: 'Reward every return well, especially around new distractions; sometimes release to continue the fun.', repeat: 'Use the line or barrier and build the skill separately rather than testing it off leash.', ready: 'Only consider more freedom where local rules, fencing, and the individual dog make it genuinely safe.' }
    ],
    success: ['Your dog turns and returns in familiar, low-distraction settings.', 'The return earns a reward and does not always signal that fun is over.', 'The handler uses a secure line or barrier instead of testing an unreliable recall.'],
    struggles: [['Your dog ignores the cue', 'Move closer, lower the distraction, and rebuild success before trying again.'], ['Your dog comes slowly', 'Reward the arrival generously; do not punish the pace or make every return end play.'], ['Your dog is fixated on a trigger', 'Do not keep calling. Create distance safely, then practice at an easier intensity another time.']],
    mistakes: [['Calling when you cannot keep the dog safe', 'Use a leash, long line, or barrier until recall is reliable in that setting.'], ['Calling only to leave the park or end play', 'Mix in rewards and safe releases back to enjoyable activities.'], ['Repeating the cue while the dog is distracted', 'Use the cue when success is likely, then adjust the setup if it is not.']],
    safety: 'Keep your dog on a secure leash near roads, wildlife, livestock, unfamiliar dogs, and open spaces unless a safe enclosed area and local rules allow otherwise. Do not rely on recall to interrupt danger. Seek qualified help if returning is linked to fear or conflict.',
    next: 'Refresh recall in short, easy games. Add distance or distraction gradually, and keep the long line or secure fence as a safety measure.',
    sources: [{ label: 'AVSAB: reward-based training position statements', href: 'https://avsab.org/resources/position-statements/' }]
  },
  {
    id: 'settle-mat', order: '09', category: 'Calm at home', title: 'Settle on a mat',
    summary: 'Help your dog choose a comfortable resting spot without asking for forced stillness.',
    image: './assets/training-settle.webp', alt: 'A dog resting on a mat beside a seated handler at home',
    overview: ['A mat can become a familiar place to relax while ordinary home life happens. The goal is voluntary rest, not holding a dog in a down-stay.', 'Some dogs need sleep, movement, food, a toilet break, or more space before they can settle. Meet those needs first.'],
    setup: [['Choose a mat', 'Use a comfortable, non-slip mat in a quiet place where the dog can leave freely.'], ['Prepare rewards', 'Have small treats ready to place low on the mat.'], ['Keep traffic low', 'Start away from visitors, children, food preparation, and busy doorways.'], ['Allow choice', 'Do not tether or block the dog from leaving the mat.']],
    stages: [
      { title: 'Let the mat become familiar', do: 'Place the mat down and wait. Do not call or lure your dog onto it.', watch: 'Notice a look, sniff, or step toward the mat.', reward: 'Mark the choice and place a treat on the mat, then let the dog step away.', repeat: 'Pause between rewards so the dog can choose to return or leave.', ready: 'Continue when the mat itself is no longer worrying and your dog approaches by choice.' },
      { title: 'Reward staying nearby', do: 'When your dog steps or stands on the mat, calmly place a treat between their front paws.', watch: 'Look for loose muscles, sniffing, or a comfortable turn away—not a rigid pose.', reward: 'Place another treat on the mat while your dog remains relaxed, then pause.', repeat: 'If they leave, let them. Reset without calling them back.', ready: 'Add a little more time between treats only while your dog chooses to remain comfortable.' },
      { title: 'Notice natural rest', do: 'During a calm moment, reward a voluntary sit, hip shift, head lowering, or lie-down on the mat.', watch: 'Compare with your dog’s normal body; soft breathing and the ability to move away matter more than a particular position.', reward: 'Place the treat gently on the mat, avoiding reaching over the dog’s face.', repeat: 'Keep the room quiet and end the practice before the dog becomes restless.', ready: 'Allow longer rests to emerge naturally; do not ask for a long stay.' },
      { title: 'Add mild everyday movement', do: 'While your dog is comfortable, make one small household movement, such as standing up and sitting down nearby.', watch: 'Look for the dog to remain loose or choose to leave without distress.', reward: 'Reward relaxed choices, and pause the activity if the dog becomes watchful or gets up repeatedly.', repeat: 'Reduce movement or return to the quieter setup when needed.', ready: 'Introduce another mild activity only after the current one no longer disrupts comfort.' }
    ],
    success: ['Your dog approaches or rests on the mat by choice.', 'The dog can leave freely and return without being called or restrained.', 'Relaxed behavior—not immobility—is what you notice and reward.'],
    struggles: [['Your dog ignores the mat', 'Try a different comfortable surface or quieter location; do not push or lure repeatedly.'], ['Your dog takes the treat and leaves', 'That is fine. Reward small voluntary visits and keep sessions low-pressure.'], ['Your dog cannot settle', 'Check for unmet needs, discomfort, heat, noise, or too much activity; pause and address those first.']],
    mistakes: [['Using the mat as a forced time-out', 'Make it a safe, voluntary resting place, not a punishment or restraint.'], ['Rewarding only a perfect down', 'Notice small signs of ease and let the dog choose their position.'], ['Adding household chaos too soon', 'Change one mild detail at a time and let the dog leave.']],
    safety: 'Never tether a dog to the mat or use it to hold them near children, visitors, or a frightening trigger. If restlessness or difficulty lying down is new, persistent, or painful, check with a veterinarian.',
    next: 'Keep the mat available as a choice. Gradually practice mild household movement while preserving a clear, quiet retreat where the dog can rest undisturbed.',
    sources: [{ label: 'AVSAB: reward-based training position statements', href: 'https://avsab.org/resources/position-statements/' }]
  },
  {
    id: 'cooperative-handling', order: '10', category: 'Care & comfort', title: 'Cooperative handling',
    summary: 'Make everyday touch predictable, rewarding, and easy for your dog to pause.',
    image: './assets/training-handling.webp', alt: 'A handler briefly touching a dog’s paw while offering a treat',
    overview: ['Cooperative handling breaks grooming and care into tiny steps and notices whether the dog is comfortable continuing.', 'This is introductory practice, not a substitute for veterinary treatment. A frightened or painful dog should not be pushed through handling.'],
    setup: [['Pick one small action', 'Choose a touch your dog already tolerates, not the hardest nail, ear, or harness step.'], ['Use a calm setting', 'Practice where the dog can move away and there are no time pressures.'], ['Prepare rewards', 'Have a reward your dog likes and can take comfortably.'], ['Agree on a pause', 'Plan to stop after each brief touch and let the dog choose whether to re-engage.']],
    stages: [
      { title: 'Practice a comfortable approach', do: 'Stand slightly sideways and briefly move your hand toward an easy area such as the shoulder, without touching at first.', watch: 'Notice whether your dog stays loose, turns away, freezes, or moves closer.', reward: 'If the dog remains comfortable, mark and reward, then let your hand move away.', repeat: 'If the dog avoids you or stiffens, stop and add distance; do not lure them closer to the hand.', ready: 'Continue when the dog can stay relaxed and freely choose to return.' },
      { title: 'Add one brief touch', do: 'Touch the easy area for about a moment, then remove your hand. Keep your body relaxed.', watch: 'Look for the dog’s whole body to remain soft and for them to stay or re-approach voluntarily.', reward: 'Offer a treat after the touch, with your hand away from the dog.', repeat: 'Pause between repetitions. If the dog leaves, end the session.', ready: 'Repeat only when the touch remains comfortable across several short tries.' },
      { title: 'Build duration or a new area separately', do: 'Choose either a slightly longer touch or a nearby body area. Change only one thing.', watch: 'Check for head turns, lip licking, paw lifts, leaning away, freezing, or attempts to leave.', reward: 'Stop touching and reward only while the dog is still comfortable.', repeat: 'Return to an easier touch if you see discomfort; do not hold the dog still.', ready: 'Try another care step on a different session after this small step stays easy.' },
      { title: 'Introduce a care item at a distance', do: 'Show a brush, towel, or harness without using it. Let your dog look or sniff, then put it away.', watch: 'Notice whether the dog can investigate and move away freely.', reward: 'Pair calm noticing with a treat, with the item still at an easy distance.', repeat: 'Move the item farther away or end the session if the dog avoids it.', ready: 'Only bring the item closer after relaxed approaches; actual use is a separate, gradual skill.' }
    ],
    success: ['Your dog can choose to stay or return after a brief touch.', 'You stop at early signs of discomfort instead of waiting for a struggle.', 'Care items predict calm rewards without being used to trap the dog.'],
    struggles: [['Your dog pulls away or freezes', 'Stop touching, let them leave, and restart later with more distance or an easier body area.'], ['Your dog will not take food', 'Do not keep going; the dog may be uncomfortable. End the session and lower difficulty next time.'], ['The dog is painful or needs urgent care', 'Pause training and contact your veterinarian for a safe care plan.']],
    mistakes: [['Holding the dog still to finish', 'Make sessions voluntary and brief; arrange professional support for necessary care.'], ['Touching repeatedly without a break', 'Remove your hand after each touch so the dog can opt in again.'], ['Moving straight to paws, ears, or nails', 'Build one comfortable step at a time and treat every new body area as a new skill.']],
    safety: 'Stop if the dog freezes, growls, snaps, hides, or tries to escape. Do not punish warning signals or reach for a guarded dog. For pain, bite risk, or essential handling the dog cannot tolerate, ask a veterinarian and a qualified reward-based behavior professional for an individualized plan.',
    next: 'Practice one easy touch for a few seconds on a calm day. Keep a record of the dog’s comfort and work with your veterinary team for medical procedures.',
    sources: [{ label: 'AVSAB: reward-based training position statements', href: 'https://avsab.org/resources/position-statements/' }]
  },
  {
    id: 'toilet-training', order: '11', category: 'Home routines', title: 'Toilet-training routine',
    summary: 'Prevent confusion with timely outdoor breaks, supervision, and immediate rewards.',
    image: './assets/training-potty.webp', alt: 'A puppy receiving a reward from its guardian in a secure grassy yard',
    overview: ['Toilet training is a routine and supervision skill, not a test of whether a dog is being “naughty.” Puppies, newly adopted dogs, and dogs in a changed home may need time and frequent chances.', 'There is no one schedule for every dog. Learn your dog’s pattern and adjust the number of opportunities to their age, health, and routine.'],
    setup: [['Pick a safe spot', 'Choose an easy-to-reach outdoor area where your dog can focus and you can reward promptly.'], ['Prepare a reward', 'Keep a small treat or another reward handy before going out.'], ['Supervise indoors', 'Stay close enough to notice sniffing, circling, or moving toward the exit. Use a safe pen or gate when you cannot watch.'], ['Plan routine outings', 'Offer a toilet chance after waking, meals or drinks, play, and before rest; add outings when your dog’s own pattern suggests.']],
    stages: [
      { title: 'Build a predictable opportunity', do: 'Take your dog to the safe spot at likely times and stay nearby quietly. Use a leash if it helps keep them safe and focused.', watch: 'Notice your dog’s personal signs and whether the spot or surface feels comfortable.', reward: 'As soon as your dog finishes, calmly praise and offer the reward outside.', repeat: 'If they do not go, return indoors with close supervision and try again later; do not turn the outing into pressure.', ready: 'Continue the routine until outdoor toileting and the reward become familiar.' },
      { title: 'Prevent indoor accidents', do: 'Keep your dog in the same room with you or behind a safe gate when they have not recently had a chance to go.', watch: 'Look for a sudden pause in play, sniffing, circling, or heading to a familiar spot or door.', reward: 'If your dog toilets outside, reward right after they finish.', repeat: 'If you notice an accident starting, calmly interrupt only if you can do so without startling them, then offer the outdoor spot.', ready: 'Give more freedom gradually as your dog’s pattern becomes predictable; supervise again after changes.' },
      { title: 'Respond calmly to an accident', do: 'If you find a mess, clean it quietly. If you catch your dog in the act, avoid startling or scolding; offer a chance to finish outside if practical.', watch: 'Look for timing or location patterns that suggest the routine needs adjustment.', reward: 'Reward future success outdoors as usual.', repeat: 'Increase supervision and add a timely outing rather than punishing the dog.', ready: 'Resume the previous level of freedom only when your dog is succeeding consistently for their own needs.' },
      { title: 'Refresh the routine after a change', do: 'After moving, travel, schedule changes, or adoption, temporarily return to more frequent outings and close supervision.', watch: 'Notice whether the dog’s usual signals or preferred surface have changed.', reward: 'Reward success in the new location just as you did before.', repeat: 'Be patient; a new setting can require relearning where to go.', ready: 'Restore freedom gradually once the dog is comfortable and the pattern is reliable.' }
    ],
    success: ['Your dog has regular chances to go before they are desperate.', 'Outdoor success is followed immediately by a calm reward.', 'Accidents lead to better supervision or schedule changes, not punishment.'],
    struggles: [['Accidents happen at predictable times', 'Add an outing before that time and supervise closely afterward.'], ['The dog does not toilet outdoors', 'Choose a quieter spot, give time without pressure, and supervise indoors before another try.'], ['A previously reliable dog starts having accidents', 'Contact your veterinarian; sudden changes can have a medical cause.']],
    mistakes: [['Expecting a young or newly adopted dog to hold it for long periods', 'Offer more frequent opportunities and tailor the routine to that dog.'], ['Scolding after an accident', 'Clean calmly and prevent the next accident with supervision.'], ['Rewarding before the dog finishes', 'Wait until toileting is complete, then reward promptly outside.']],
    safety: 'Ask a veterinarian promptly about new or frequent accidents, straining, blood, pain, excessive thirst, or other unusual changes. Do not restrict water or punish accidents. Use secure leashes and gates in outdoor or indoor spaces where escape or injury is possible.',
    next: 'Keep a simple note of outing times and successes for a few days. Use that pattern to adjust the routine, and get veterinary help for sudden changes.',
    sources: [{ label: 'Dogs Trust: house or toilet training', href: 'https://www.dogstrust.org.uk/dog-advice/training/basics/house-or-toilet-training' }]
  },
  {
    id: 'positive-socialization', order: '12', category: 'Confidence & new experiences', title: 'Positive socialization',
    summary: 'Help your dog feel safe around new sights and sounds—without forcing greetings.',
    image: './assets/training-socialization.webp', alt: 'A puppy observing a passerby from a comfortable distance beside its guardian',
    overview: ['Socialization is safe, positive exposure to people, animals, places, sounds, surfaces, and daily handling—not a requirement to meet everyone.', 'The dog’s comfort matters more than how close or how many things they experience. Puppies’ health and local infection risks make it important to plan exposure with your veterinarian.'],
    setup: [['Choose one experience', 'Pick a calm person at a distance, a quiet sound, or one new surface—not several new things together.'], ['Find a safe distance', 'Start far enough away that your dog can sniff, take a reward, and look away or leave.'], ['Bring a familiar reward', 'Use food or play your dog already likes; do not lure them toward the new thing.'], ['Plan an exit', 'Choose a route or barrier that lets you increase distance immediately.']],
    stages: [
      { title: 'Notice from a comfortable distance', do: 'Let your dog observe one new person, sound, or object from far enough away that they can still move freely.', watch: 'Look for loose movement, sniffing, blinking, taking food, or choosing to look away. Watch the whole body.', reward: 'When your dog notices the experience, calmly offer a reward or let them sniff; do not require eye contact.', repeat: 'Keep the exposure brief. If the dog freezes, hides, pulls away, or cannot take food, increase distance and end the try.', ready: 'Repeat only when your dog remains comfortable and can recover quickly at this distance.' },
      { title: 'Pair the experience with something good', do: 'At the same comfortable distance, let the new sight or sound appear briefly, then allow it to pass.', watch: 'Notice whether your dog stays able to explore and turn away rather than fixate or retreat.', reward: 'Offer a small treat or favorite activity while the dog is still relaxed.', repeat: 'If worry increases, stop the exposure and move to a quieter place.', ready: 'Keep the distance the same until the dog’s response remains relaxed across separate short experiences.' },
      { title: 'Vary one easy detail', do: 'Try the same type of experience in a new calm place or with a slightly different person, changing only one detail.', watch: 'A familiar sight may feel new in another context; watch for recovery and choice.', reward: 'Continue rewarding calm observation and give the dog permission to leave.', repeat: 'Return to the easier location or add distance if the dog becomes unsure.', ready: 'Try another small variation only when this one is comfortable.' },
      { title: 'Let greetings be optional', do: 'If you plan a greeting, ask the person to remain still and let the dog approach or not. Keep the leash loose and provide space.', watch: 'A dog who turns away, moves back, freezes, or stops engaging is asking for more space.', reward: 'Reward calm choices and guide your dog away before they feel trapped.', repeat: 'Do not ask for repeated greetings; watching from a distance is useful practice too.', ready: 'Build only the kinds of exposure your dog chooses and can recover from.' }
    ],
    success: ['Your dog can notice the experience and still sniff, take food, or look away.', 'The dog can increase distance or opt out without being followed.', 'Recovery stays easy, and greetings remain optional.'],
    struggles: [['Your dog freezes, hides, or pulls away', 'End the exposure, increase distance, and let them recover in a familiar safe place.'], ['Your dog barks or lunges', 'Move away calmly and manage the environment; do not force closer exposure. Seek qualified help if repeated or unsafe.'], ['Your puppy is not fully vaccinated', 'Ask your veterinarian about local disease risks and safe ways to experience the world; avoid unknown dogs and contaminated areas as advised.']],
    mistakes: [['Assuming socialization means meeting many dogs', 'Choose calm, controlled observations; safe distance is valuable.'], ['Luring a worried puppy closer for a treat', 'Keep rewards with you so the puppy can eat without approaching what worries them.'], ['Forcing greetings or holding the dog in place', 'Allow choice and provide an easy exit.']],
    safety: 'Never place a dog in a crowded or uncontrolled setting to “get used to it.” Use secure equipment and follow your veterinarian’s advice about vaccination, parasites, and local risks. For persistent fear, panic, or aggression, stop exposure exercises and consult a veterinarian or qualified behavior professional.',
    next: 'Offer brief, positive experiences over time. Keep a comfortable distance, let the dog opt out, and build variety only when they remain relaxed.',
    sources: [
      { label: 'AVSAB: puppy socialization position statement', href: 'https://avsab.org/resources/position-statements/' },
      { label: 'AAHA: canine behavior guidance', href: 'https://www.aaha.org/resources/life-stage-canine-2019/behavior/' }
    ]
  }
];
